### PR TITLE
Open Transport Request popup on click

### PR DESCRIPTION
**Pull request by oisee**
Open Transport Request popup on click

Added "praise" program (someone just does not want to be ZBLAMED =).
Added navigation to SE10 popup on "transport request" click (to the left of a source code line, and at the bottom "Requests" list)

### CODE REVIEW

**Comment by oisee** [comment]
This is my first PR =) so it might be not really conventional =) Sorry for that.

**Comment by nununo** [comment]
Hi @oisee,

Thanks so much for the PR! The first one :)
I'm quite busy right now so it will take me some days to give this the attention it deserves. I'm writing this just so that you know it's not being ignored.

Cheers!

**Comment by oisee** [comment]
> Hi @oisee,
> 
> Thanks so much for the PR! The first one :)
> I'm quite busy right now so it will take me some days to give this the attention it deserves. I'm writing this just so that you know it's not being ignored.
> 
> Cheers!

Thank you for such an amazing tool =)

(BTW, it is my first PR, so, feel free to reject and make me do it properly :D )

**Comment by nununo** [comment]
Hi there @oisee,

I finally found some time for this project. Long due.

Regarding your PR, I won't be able to merge it for 3 reasons:

- You applied _pretty printer_ to the code which yields lots and lots of differences. Any change you make must keep the current formatting so that we can easily see what was really changed
- I found the `PRAISE` program funny, but I called it `BLAME` because this is a [known git concept](https://www.git-scm.com/docs/git-blame) so it really makes sense to stick to the same name. Sorry :-)
- You're right! A lot of fundamental links are needed! But actually I had already added links to the requests and authors several months ago. Unfortunately I was unable to submit those changes at the time (actually today I tried again to submitted and found that I am still getting an authentication error. I'll have to figure out what's wrong). I am sorry about this.

Your future PRs are more than welcome. I suggest, though, that you **first submit an issue and propose to implement it**. This way we can discuss it before you go along and implement it, to avoid wasted work.

Thanks again! And I'm glad you like this tool. I also find it quite useful!

Cheers!

**Comment by oisee** [comment]
@nununo, tnx for the feedback =)

>I found the PRAISE program funny, but I called it BLAME because this is a known git concept so it really makes sense to stick to the same name. Sorry :-)

Yes, that was just for fun. (But I wonder if you are aware of sporadic attempts to add the "praise" alias to the GIT? I remember this kind of news since ~5 y ago or so. =) And yes, some of those who are not exposed to the GIT concepts feel a bit wounded when "BLAMED", so why not to PRAISE them (Snowflake feelings matter =)

Tnx for the suggestion to log the issue first, to be able to discuss. (Yes, I implemented the "feature" first (after pretty printing which cannot be undone) and only then realized that I can do PR =)

Tnx a million.

Best regards, Ilia.

**Comment by nununo** [comment]
Hi @oisee,

Oh, I didn't know that there had been a actual discussion about praise/blame lol. That makes your joke even more funny.

Regarding pretty printer, I'm also struggling with it because Eclipse automatically reformats the code and even reorders the method implementations. I still don't have a solution for it. I'll probably have to start editing things in SE24 again :p 

I don't know if you saw my last commits but the links to requests and to the source code are now in place. The link to the author is already in there but it doesn't work and I still didn't figure out why. Probably a detail in how the FM is called.

Thanks again for your contribution and enthusiasm!

Cheers,
Nuno

**Pull request closed without merging**
